### ISSUE TITLE
ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by CHASII** [siyangbing/baiduwenku#1]
CentOS7环境：
Collecting opencv-python (from -r requirements.txt (line 4))
  Downloading http://mirrors.tencentyun.com/pypi/packages/30/46/821920986c7ce5bae5518c1d490e520a9ab4cef51e3e54e35094dadf0d68/opencv-python-4.4.0.46.tar.gz (88.9MB)
    100% |████████████████████████████████| 88.9MB 76.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j487ohxv/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'

**Comment by siyangbing** [comment]
try this

pip install sklearn
